"""empty message

Revision ID: d0c3236a6ae6
Revises: f48fe0cfff21
Create Date: 2020-10-24 04:39:30.964542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0c3236a6ae6'
down_revision = 'f48fe0cfff21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username', nullable=False, new_column_name='name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name', nullable=False, new_column_name='username')
    # ### end Alembic commands ###
